import ast
from pathlib import Path

from remote_mcp.sources.openapi.introspect import (
    OperationModel,
    ParamModel,
    extract_operations,
    load_spec,
)
from remote_mcp.sources.openapi.render import render_openapi_tools

FIXTURE = Path(__file__).parent / "fixtures" / "petstore.json"


def render():
    spec, _ = load_spec(str(FIXTURE))
    return render_openapi_tools(
        "petstore",
        extract_operations(spec),
        generator_version="1.0.0",
        locator=str(FIXTURE),
    )


def _op(
    operation_id: str,
    func_name: str,
    path: str,
    path_fstring: str,
    summary: str,
    tags: list[str],
    params: list[ParamModel],
    method: str = "get",
) -> OperationModel:
    return OperationModel(
        operation_id=operation_id,
        func_name=func_name,
        method=method,
        path=path,
        path_fstring=path_fstring,
        summary=summary,
        tags=tags,
        params=params,
    )


def test_file_layout():
    files = render()
    assert set(files) == {
        "src/tools/petstore/__init__.py",
        "src/tools/petstore/pets.py",
        "tests/tools/test_petstore_pets.py",
    }


def test_generated_module_is_valid_python_with_expected_symbols():
    files = render()
    mod = files["src/tools/petstore/pets.py"]
    tree = ast.parse(mod)  # must compile
    func_names = {n.name for n in ast.walk(tree) if isinstance(n, ast.AsyncFunctionDef)}
    assert {"list_pets", "get_pet_by_id", "create_pet"} <= func_names
    assert "petstore_pets_router = FastMCP(" in mod
    assert "remote_mcp" not in mod  # zero runtime dep
    assert "generated by remote-mcp 1.0.0" in mod  # header
    assert 'f"/pets/{pet_id}"' in mod  # path params rewritten


def test_error_mapping_present():
    mod = render()["src/tools/petstore/pets.py"]
    for name in ("AuthError", "ForbiddenError", "ValidationError", "BackendError"):
        assert name in mod


def test_generated_test_file_valid_python():
    test_mod = render()["tests/tools/test_petstore_pets.py"]
    ast.parse(test_mod)
    assert "test_check_maps_status" in test_mod


def test_reserved_param_names_renamed():
    op = _op(
        "doThing",
        "do_thing",
        "/thing",
        "/thing",
        "Do thing",
        ["ops"],
        [
            ParamModel(name="ctx", py_type="str", required=False, location="query"),
            ParamModel(name="query", py_type="str", required=False, location="query"),
            ParamModel(name="class", py_type="str", required=False, location="body"),
        ],
    )
    files = render_openapi_tools("api", [op], generator_version="1.0.0", locator="test")
    mod = files["src/tools/api/ops.py"]
    ast.parse(mod)  # must compile
    assert "ctx_: str" in mod
    assert "query_: str" in mod
    assert "class_: str" in mod
    assert 'query["ctx"]' in mod
    assert 'query["query"]' in mod
    assert 'body["class"]' in mod


def test_path_param_keyword_renamed():
    op = _op(
        "getItem",
        "get_item",
        "/items/{from}",
        "/items/{from}",
        "Get item",
        ["items"],
        [ParamModel(name="from", py_type="str", required=True, location="path")],
    )
    files = render_openapi_tools("api", [op], generator_version="1.0.0", locator="test")
    mod = files["src/tools/api/items.py"]
    ast.parse(mod)  # must compile
    assert 'f"/items/{from_}"' in mod


def test_messy_tag_grouped_safely():
    op = _op(
        "listThings",
        "list_things",
        "/things",
        "/things",
        "List things",
        ["Pet Store.v2"],
        [],
    )
    files = render_openapi_tools("x", [op], generator_version="1.0.0", locator="test")
    assert "src/tools/x/pet_store_v2.py" in files
    mod = files["src/tools/x/pet_store_v2.py"]
    ast.parse(mod)  # must compile
    assert "x_pet_store_v2_router = FastMCP(" in mod


def test_evil_summary_escaped():
    op = _op(
        "sayHi",
        "say_hi",
        "/hi",
        "/hi",
        'Say "hi"\n"""break"""',
        ["misc"],
        [],
    )
    files = render_openapi_tools("api", [op], generator_version="1.0.0", locator="test")
    mod = files["src/tools/api/misc.py"]
    ast.parse(mod)  # must compile


def test_duplicate_func_names_deduped():
    op1 = _op("listThingsA", "list_things", "/a", "/a", "List A", ["dup"], [])
    op2 = _op("listThingsB", "list_things", "/b", "/b", "List B", ["dup"], [])
    files = render_openapi_tools("api", [op1, op2], generator_version="1.0.0", locator="test")
    mod = files["src/tools/api/dup.py"]
    tree = ast.parse(mod)  # must compile
    func_names = {n.name for n in ast.walk(tree) if isinstance(n, ast.AsyncFunctionDef)}
    assert {"list_things", "list_things_2"} <= func_names


def test_camelcase_wire_names():
    op = _op(
        "getPetById",
        "get_pet_by_id",
        "/pets/{pet_id}",
        "/pets/{pet_id}",
        "Get a pet",
        ["pets"],
        [
            ParamModel(
                name="pet_id",
                py_type="str",
                required=False,
                location="query",
                wire_name="petId",
            )
        ],
    )
    files = render_openapi_tools("api", [op], generator_version="1.0.0", locator="test")
    mod = files["src/tools/api/pets.py"]
    ast.parse(mod)  # must compile
    assert 'query["petId"]' in mod
    assert 'query["pet_id"]' not in mod


def test_keyword_operation_id_sanitized():
    op = _op("import", "import", "/imports", "/imports", "Import", ["misc"], [])
    files = render_openapi_tools("api", [op], generator_version="1.0.0", locator="test")
    mod = files["src/tools/api/misc.py"]
    ast.parse(mod)  # must compile
    assert "async def import_" in mod


def test_digit_prefix_operation_id():
    op = _op("2faCheck", "2fa_check", "/2fa", "/2fa", "2FA check", ["misc"], [])
    files = render_openapi_tools("api", [op], generator_version="1.0.0", locator="test")
    mod = files["src/tools/api/misc.py"]
    ast.parse(mod)  # must compile
    assert "async def op_2fa_check" in mod


def test_dotted_operation_id():
    op = _op("pets.list", "pets.list", "/pets", "/pets", "List pets", ["pets"], [])
    files = render_openapi_tools("api", [op], generator_version="1.0.0", locator="test")
    mod = files["src/tools/api/pets.py"]
    ast.parse(mod)  # must compile
    assert "async def pets_list" in mod


def test_keyword_tag_group():
    op = _op("listThings", "list_things", "/things", "/things", "List things", ["class"], [])
    files = render_openapi_tools("api", [op], generator_version="1.0.0", locator="test")
    assert "src/tools/api/class_.py" in files
    test_mod = files["tests/tools/test_api_class_.py"]
    ast.parse(test_mod)  # import line (`from src.tools.api import class_ as mod`) must parse


def test_empty_summary_falls_back_sanitized():
    op = _op('evil"""id', "evil_id", "/evil", "/evil", "", ["misc"], [])
    files = render_openapi_tools("api", [op], generator_version="1.0.0", locator="test")
    mod = files["src/tools/api/misc.py"]
    ast.parse(mod)  # must compile


def test_unordered_params_sorted():
    op = _op(
        "listThings",
        "list_things",
        "/things",
        "/things",
        "List things",
        ["things"],
        [
            ParamModel(name="optional_p", py_type="str", required=False, location="query"),
            ParamModel(name="required_p", py_type="str", required=True, location="query"),
        ],
    )
    files = render_openapi_tools("api", [op], generator_version="1.0.0", locator="test")
    mod = files["src/tools/api/things.py"]
    ast.parse(mod)  # must compile: required param can't follow a defaulted one
