"""Drift checks: manifest vs reality (files, versions, live sources)."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path

from remote_mcp import __version__
from remote_mcp.sources.manifest import (
    MANIFEST_NAME,
    Manifest,
    ManifestError,
    hash_bytes,
    load_manifest,
)

_SQLITE_PREFIX = "sqlite:///"


@dataclass
class FileStatus:
    path: str
    status: str  # "clean" | "modified" | "missing"


@dataclass
class SourceStatus:
    name: str
    kind: str
    version_drift: str  # "" = none
    files: list[FileStatus] = field(default_factory=list)
    source_drift: str = "skipped"  # "current" | "drifted" | "unreachable" | "skipped"


@dataclass
class DoctorReport:
    sources: list[SourceStatus] = field(default_factory=list)

    @property
    def has_drift(self) -> bool:
        return any(
            s.version_drift
            or s.source_drift == "drifted"
            or any(f.status != "clean" for f in s.files)
            for s in self.sources
        )

    def to_dict(self) -> dict:
        return {"has_drift": self.has_drift, "sources": [asdict(s) for s in self.sources]}


def _resolve_sqlite_path(locator: str, project_dir: Path) -> Path:
    """Resolve a `sqlite:///...` locator's filesystem path against project_dir.

    Manifests may store a relative sqlite path (e.g. `sqlite:///data.db`); it
    is relative to the project directory it was generated in, not to
    whatever directory `doctor --refresh` happens to be invoked from.
    """
    db_path = Path(locator[len(_SQLITE_PREFIX) :])
    if not db_path.is_absolute():
        db_path = project_dir / db_path
    return db_path


def _sqlite_missing(locator: str, project_dir: Path) -> bool:
    """True when `locator` is a sqlite DSN whose backing file does not exist.

    SQLAlchemy silently *creates* an empty sqlite file when you introspect a
    nonexistent path instead of failing, so this must be checked up front —
    calling `introspect_database` on a missing sqlite path would otherwise
    fabricate a database as a side effect of running `doctor --refresh`.
    """
    if not locator.startswith(_SQLITE_PREFIX):
        return False
    return not _resolve_sqlite_path(locator, project_dir).exists()


def _refresh_status(entry, project_dir: Path) -> str:
    try:
        if entry.kind == "openapi":
            from remote_mcp.sources.openapi.introspect import load_spec

            locator = entry.locator
            if not locator.startswith(("http://", "https://")):
                spec_path = Path(locator)
                if not spec_path.is_absolute():
                    spec_path = project_dir / spec_path
                locator = str(spec_path)
            _, digest = load_spec(locator)
        else:
            dsn = entry.locator
            if dsn.startswith(_SQLITE_PREFIX):
                if _sqlite_missing(dsn, project_dir):
                    return "unreachable"
                dsn = f"{_SQLITE_PREFIX}{_resolve_sqlite_path(dsn, project_dir)}"

            from remote_mcp.sources.database.introspect import (
                introspect_database,
                schema_fingerprint,
            )

            # locator is sanitized (no credentials) — refresh only works when
            # the DSN needs none (e.g. sqlite). Otherwise report unreachable.
            tables = introspect_database(dsn)
            selected = [t for t in tables if t.name in set(entry.selected)]
            digest = schema_fingerprint(selected)
        return "current" if digest == entry.source_sha256 else "drifted"
    except Exception:
        return "unreachable"


def run_doctor(project_dir: Path, refresh: bool = False) -> DoctorReport:
    project_dir = Path(project_dir)
    manifest: Manifest = load_manifest(project_dir)
    if not manifest.sources:
        raise ManifestError(
            f"No {MANIFEST_NAME} with sources found. Generate one with "
            "`remote-mcp add openapi` or `remote-mcp add database`."
        )
    report = DoctorReport()
    for entry in manifest.sources:
        status = SourceStatus(name=entry.name, kind=entry.kind, version_drift="")
        if entry.generator_version != __version__:
            status.version_drift = (
                f"generated by {entry.generator_version}, installed {__version__} — "
                "templates may have changed"
            )
        for gf in entry.generated_files:
            target = project_dir / gf.path
            if not target.exists():
                status.files.append(FileStatus(gf.path, "missing"))
            elif hash_bytes(target.read_bytes()) != gf.sha256:
                status.files.append(FileStatus(gf.path, "modified"))
            else:
                status.files.append(FileStatus(gf.path, "clean"))
        if refresh:
            status.source_drift = _refresh_status(entry, project_dir)
        report.sources.append(status)
    return report
